//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdscecEntities : DbContext
    {
        public bdscecEntities()
            : base("name=bdscecEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ciudad> ciudad { get; set; }
        public virtual DbSet<estados> estados { get; set; }
        public virtual DbSet<personas> personas { get; set; }
        public virtual DbSet<pregunta> pregunta { get; set; }
        public virtual DbSet<resultado> resultado { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<seccion> seccion { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<test> test { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<usuarioRol> usuarioRol { get; set; }
    }
}
