//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ciudad
    {
        public ciudad()
        {
            this.personas = new HashSet<personas>();
        }
    
        public int id { get; set; }
        public int idEstado { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
    
        public virtual estados estados { get; set; }
        public virtual ICollection<personas> personas { get; set; }
    }
}
