//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.usuarioRol = new HashSet<usuarioRol>();
        }
    
        public int id { get; set; }
        public string nombreApellidoPaterno { get; set; }
        public string nombreApellidoMaterno { get; set; }
    
        public virtual ICollection<usuarioRol> usuarioRol { get; set; }
    }
}
