//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantenimiento.idiomas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class idiomas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal idiomas() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mantenimiento.Properties.idiomas", typeof(idiomas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe los campos correspondientes.
        /// </summary>
        public static string aux_modal {
            get {
                return ResourceManager.GetString("aux_modal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar Operacion.
        /// </summary>
        public static string boton_cancelar {
            get {
                return ResourceManager.GetString("boton_cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string boton_eliminar {
            get {
                return ResourceManager.GetString("boton_eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string boton_guardar {
            get {
                return ResourceManager.GetString("boton_guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar cambios.
        /// </summary>
        public static string boton_modificar {
            get {
                return ResourceManager.GetString("boton_modificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar .
        /// </summary>
        public static string boton_nuevo {
            get {
                return ResourceManager.GetString("boton_nuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar.
        /// </summary>
        public static string boton_opcion_modificar {
            get {
                return ResourceManager.GetString("boton_opcion_modificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar.
        /// </summary>
        public static string boton_regresar {
            get {
                return ResourceManager.GetString("boton_regresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catálogo de Personas.
        /// </summary>
        public static string catalogo_personas {
            get {
                return ResourceManager.GetString("catalogo_personas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catálogos de Preguntas.
        /// </summary>
        public static string catalogo_preguntas {
            get {
                return ResourceManager.GetString("catalogo_preguntas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INICIAR TEST.
        /// </summary>
        public static string cuestionario_inicio {
            get {
                return ResourceManager.GetString("cuestionario_inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciudades.
        /// </summary>
        public static string menu_ciudad {
            get {
                return ResourceManager.GetString("menu_ciudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estados.
        /// </summary>
        public static string menu_estados {
            get {
                return ResourceManager.GetString("menu_estados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personas.
        /// </summary>
        public static string menu_personas {
            get {
                return ResourceManager.GetString("menu_personas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administracion de preguntas.
        /// </summary>
        public static string titulo_preguntas {
            get {
                return ResourceManager.GetString("titulo_preguntas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administracion  de secciones.
        /// </summary>
        public static string titulo_secciones {
            get {
                return ResourceManager.GetString("titulo_secciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administracion de test.
        /// </summary>
        public static string titulo_test {
            get {
                return ResourceManager.GetString("titulo_test", resourceCulture);
            }
        }
    }
}
